<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <DefineConstants>$(DefineConstants);DUENDE</DefineConstants>
    <RootNamespace>Abc.IdentityServer.Saml2.EntityFramework</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abc.IdentityServer4.Saml2\Abc.DuendeIdentityServer.Saml2.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Duende.IdentityServer.EntityFramework.Storage" Version="6.*" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Duende.IdentityServer.EntityFramework.Storage" Version="7.*" />
  </ItemGroup>

</Project>
