<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <LangVersion>10.0</LangVersion>
    <DefineConstants>$(DefineConstants);IDS4</DefineConstants>
    <RootNamespace>Abc.IdentityServer.Saml2</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Abc.IdentityServer4.Saml2\Abc.IdentityServer4.Saml2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityServer4.EntityFramework.Storage" Version="4.1.2" />
  </ItemGroup>

</Project>
