<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Endpoints\Results\LogoutPageResultFixture.cs" />
    <Compile Remove="Services\SessionLogoutContextFixture.cs" />
    <Compile Remove="SessionLogoutContextFixture.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Endpoints\Results\LogoutPageResultFixture.cs" />
    <None Include="Services\SessionLogoutContextFixture.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Abc.IdentityServer4.Saml2\Abc.IdentityServer4.Saml2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="idsrvtest.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
