<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <LangVersion>10.0</LangVersion>
    <DefineConstants>$(DefineConstants);IDS4</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <Description>SAML2 protocol for IdentityServer4</Description>
  </PropertyGroup>  
  
  <ItemGroup>
    <Compile Remove="Endpoints\Results\LogoutPageResult.cs" />
    <Compile Remove="Endpoints\Saml2SingleLogOutEndpoint.cs" />
    <Compile Remove="Extensions\HttpRequestExtensions.cs" />
    <Compile Remove="Services\Artifact4HandleGenerationService.cs" />
    <Compile Remove="Services\IArtifactHandleGenerationService.cs" />
    <Compile Remove="Services\SessionLogoutContext.cs" />
    <Compile Remove="Services\SingleLogoutService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Endpoints\Results\LogoutPageResult.cs" />
    <None Include="Endpoints\Saml2SingleLogOutEndpoint.cs" />
    <None Include="Extensions\HttpRequestExtensions.cs" />
    <None Include="Services\Artifact4HandleGenerationService.cs" />
    <None Include="Services\IArtifactHandleGenerationService.cs" />
    <None Include="Services\SessionLogoutContext.cs" />
    <None Include="Services\SingleLogoutService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityServer4" Version="4.1.2" />
    <PackageReference Include="IdentityServer4.Storage" Version="4.1.2" />
    <PackageReference Include="Abc.IdentityModel.Http" Version="2.3.0" />
    <PackageReference Include="Abc.IdentityModel.Http.Saml" Version="2.3.0" />
    <PackageReference Include="Abc.IdentityModel.Metadata" Version="2.3.0" />
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scrutor" Version="3.3.0" />
  </ItemGroup>
</Project>
