<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />  
  <PropertyGroup>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/abc-software/Abc.IdentityServer4.Saml2</PackageProjectUrl>
    <PackageTags>ASP.NET Core;identityserver;idsrv;saml2p;authentication;auth;security</PackageTags>
    
    <RepositoryUrl>https://github.com/abc-software/Abc.IdentityServer4.Saml2.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    
    <Version>2.0.0-dev12</Version>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ids.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(MSBuildProjectName)' == 'Abc.IdentityServer4.Saml2' or '$(MSBuildProjectName)' == 'Abc.IdentityServer4.Saml2.EntityFramework.Storage'">
    <BaseIntermediateOutputPath>obj\IDS4\</BaseIntermediateOutputPath>
    <OutputPath>bin\IDS4\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(MSBuildProjectName)' == 'Abc.DuendeIdentityServer.Saml2' or '$(MSBuildProjectName)' == 'Abc.DuendeIdentityServer.Saml2.EntityFramework.Storage'">
    <BaseIntermediateOutputPath>obj\DuendeIDS\</BaseIntermediateOutputPath>
    <OutputPath>bin\DuendeIDS\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.NetFramework.Analyzers" Version="3.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="9.32.0.97167">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.11.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.0" PrivateAssets="All" /> -->
  </ItemGroup>
</Project>