name: CI

on:
  push:
    branches: [ "master" ]
    tags: [ '[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  publish-to-nuget:
    name: Publish to NuGet
    runs-on: ubuntu-latest

    needs: build

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release --no-build --include-symbols --output ${{ github.workspace }}/Packages
    - name: Publish
      run: dotnet nuget push '${{ github.workspace }}/Packages/*.*' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
